In [52]:
import argparse
import shutil

import numpy as np
import torch
from torch.autograd import Variable, grad
from torch.nn.init import xavier_normal
from torchvision import datasets, transforms
import torchvision.utils as vutils
import pandas as pd
from data import *
from bigmodels import *
from util import *
import time

In [53]:
generator = Generator()
generator.apply(weights_init)
checkpoint = torch.load('./models_big/Epoch:_042.pt')
generator.load_state_dict(checkpoint['g_state_dict'])
generator = generator.cuda()

In [54]:
def edit(tar):
    allone = [1.0 for i in range(32)]
    allzero =[0.0 for i in range(32)]
    out = []
    for i in tar:
        tmp = []
        for j in range(4):
            if j == i:
                tmp += allzero
            else:
                tmp += allone
        out.append(tmp)
    out = torch.FloatTensor(out)
    return out.cuda()

In [55]:
def get_image(model,target):
    #target = np.array(target)
    tags = torch.FloatTensor(target).cuda()
    target = np.array(target)
    batch_size = target.shape[0]
    embedding = nn.Embedding(batch_size,128).cuda()
    max_tag = np.argmax(target,axis = 1)
  
    z = Variable(torch.FloatTensor(batch_size, 128))
    z = z.cuda()
    z.data.fill_(0.0)
    z.data.normal_(0, 1)

    tag = torch.LongTensor(max_tag).cuda()
    embed = embedding(tag).view(batch_size,-1).cuda()
    xx = z.mul(embed)
    factor = edit(max_tag)
    x = xx.mul(factor)
    print(x.data)
    print(tags.data)
    
    rep = torch.cat((x, tags.clone()), 1)
    print(rep.data[0])
    fake = model.forward(rep).detach()
    return fake

In [56]:
batch_size = 64

In [57]:
k = 0

In [58]:
tag = [[1 if _ == k else 0 for _ in range(4)] for i in range(batch_size)]

In [59]:
tag

[[1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 0, 0]]

In [60]:
fake = get_image(generator,tag)


tensor([[-0.0000, -0.0000,  0.0000,  ...,  0.2687, -0.3329, -0.7485],
        [-0.0000, -0.0000,  0.0000,  ...,  1.6458,  0.0922,  0.4190],
        [ 0.0000,  0.0000, -0.0000,  ..., -0.3017, -0.9919, -0.9196],
        ...,
        [-0.0000, -0.0000,  0.0000,  ..., -2.9117, -1.0355, -0.9500],
        [ 0.0000, -0.0000, -0.0000,  ...,  0.5999, -0.0467, -0.6302],
        [-0.0000,  0.0000,  0.0000,  ..., -0.1360,  0.2025,  0.7845]],
       device='cuda:0')
tensor([[1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0

In [61]:
vutils.save_image(fake.data.view(batch_size, 3, imsize, imsize),
                    'samples/nnnn_epoch_%03d.png' % k)
del fake
torch.cuda.empty_cache()

In [36]:
tag.shape

AttributeError: 'list' object has no attribute 'shape'

In [13]:
zz = nn.Embedding(batch_size,128)

In [14]:
tags = torch.LongTensor(np)

In [15]:
em = zz(tags).view(batch_size,-1)

In [16]:
em.data.shape

torch.Size([8, 128])

In [17]:
em.data

tensor([[-1.8662, -0.6780,  0.0629,  ...,  0.2260,  1.9956,  0.6394],
        [ 0.2085, -1.5159, -1.6388,  ..., -0.3144, -0.5329,  1.0970],
        [-1.8662, -0.6780,  0.0629,  ...,  0.2260,  1.9956,  0.6394],
        ...,
        [-1.8662, -0.6780,  0.0629,  ...,  0.2260,  1.9956,  0.6394],
        [-1.8662, -0.6780,  0.0629,  ...,  0.2260,  1.9956,  0.6394],
        [ 0.2085, -1.5159, -1.6388,  ..., -0.3144, -0.5329,  1.0970]])

In [244]:
z = Variable(torch.FloatTensor(batch_size, z_dim))
tags = Variable(torch.from_numpy(tag)).float()

In [245]:
z,tags = z.cuda(),tags.cuda()

In [246]:
em = em.cuda()

In [247]:
tags.data

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], device='cuda:0')

In [248]:
z.data.normal_(0, 1)
#tags.data.uniform_(to=1) 

tensor([[-0.6285, -0.9074, -0.6732,  ..., -0.0824,  0.8979,  0.3150],
        [ 1.6532,  0.0454, -0.6051,  ...,  1.2805,  0.3189,  0.7304],
        [-0.3078,  0.1055,  0.3829,  ..., -0.4702, -0.3605,  2.5386],
        ...,
        [ 1.6482,  1.3484, -1.5093,  ..., -0.2790, -0.2140, -1.7323],
        [ 0.1852, -0.3321,  2.7310,  ..., -2.3765, -0.3010,  0.9341],
        [-0.2299, -0.7284, -0.2719,  ...,  0.0997, -0.7901, -1.7075]],
       device='cuda:0')

In [249]:
z = z.mul(em)

In [250]:
z.data

tensor([[-9.5876e-01,  4.8204e-03,  4.2808e-01,  ...,  3.2012e-02,
         -1.2923e+00,  2.9748e-01],
        [ 2.5220e+00, -2.4129e-04,  3.8477e-01,  ..., -4.9731e-01,
         -4.5892e-01,  6.8975e-01],
        [-4.6957e-01, -5.6054e-04, -2.4349e-01,  ...,  1.8259e-01,
          5.1885e-01,  2.3971e+00],
        ...,
        [ 2.5143e+00, -7.1632e-03,  9.5975e-01,  ...,  1.0835e-01,
          3.0794e-01, -1.6358e+00],
        [ 2.8248e-01,  1.7644e-03, -1.7367e+00,  ...,  9.2296e-01,
          4.3316e-01,  8.8206e-01],
        [-3.5076e-01,  3.8694e-03,  1.7287e-01,  ..., -3.8720e-02,
          1.1372e+00, -1.6124e+00]], device='cuda:0')

In [251]:
rep = torch.cat((z, tags.clone()), 1)
fake = generator.forward(rep).detach()

In [252]:
epoch = 1
vutils.save_image(fake.data.view(batch_size, 3, imsize, imsize),
                    'samples/nnnn_epoch_%03d.png' % epoch)

In [44]:
allone = [1.0 for i in range(32)]
allzero =[0.0 for i in range(32)]

In [45]:
aa = np.random.randint(4,size = 8)

In [46]:
aa

array([2, 0, 2, 1, 2, 0, 3, 3])

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [1., 1., 1.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [1., 1., 1.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 1., 1., 1.],
        [0., 0., 0.,  ..., 1., 1., 1.]])